### GET (Basic)
http://localhost:5000

### GET Projects (ALL)
http://localhost:5000/api/projects
https://wme-projects-api-v2.herokuapp.com/api/projects

### GET Actions (ALL)
http://localhost:5000/api/projects/1/actions

### GET Projects (by ID)
http://localhost:5000/api/projects/13

### GET Actions (ID)
http://localhost:5000/api/projects/2/actions/4

### POST (Projects)
POST http://localhost:5000/api/projects HTTP/1.1
content-type: application/json

{
  "name": "API Database Deployment",
  "description": "Deploy Database to AWS RDS platform",
  "is_complete": false
}

### POST (Actions)
POST http://localhost:5000/api/projects/13/actions HTTP/1.1
content-type: application/json

{
  "description": "Create AWS account",
  "project_id": 13,
  "notes": "Go to https://aws.amazon.com and sign up for a 'Free Tier' account",
  "is_complete": false
}

### PUT (Project)
PUT http://localhost:5000/api/projects/12 HTTP/1.1
content-type: application/json

{
  "name": "My Test Project #1",
  "description": "Test project details",
  "is_complete": false
}

### PUT (Action)
PUT http://localhost:5000/api/projects/12/actions/16 HTTP/1.1
content-type: application/json

{
  "description": "Kick off test project",
  "project_id": 12,
  "notes": "Let's get it started.",
  "is_complete": true
}

### DELETE (Projects)
DELETE http://localhost:5000/api/projects/4

### DELETE (Actions)
DELETE http://localhost:5000/api/projects/1/actions/3

